### ISSUE TITLE
exchange1c_product_disable_if_zero !== exchange1c_product_status_disable_if_quantity_zero

### ISSUE THREAD

**Issue by Nks** [KirilLoveVE/opencart2-exchange1c#10]
Неправильно забирается значение из конфига: https://github.com/KirilLoveVE/opencart2-exchange1c/blob/master/upload/admin/model/tool/exchange1c.php#L3441
В фронтенде `exchange1c_product_disable_if_zero`.

**Comment by KirilLoveVE** [comment]
Спасибо, все некогда было добраться до этой опции, исправил в 1.6.2.b10
