### ISSUE TITLE
не устанавливается на ocStore 2.1.0.2.1

### ISSUE THREAD

**Issue by Dragonim** [KirilLoveVE/opencart2-exchange1c#11]
Поднял новый ни чем не испорченный образ ocStore 2.1.0.2.1

Настроил FTP указав имя и пароль, параметр "FTP Каталог" оставил пустым. Начал загружать последнюю сборку, но появилась ошибка.

**Comment by KirilLoveVE** [comment]
Какая ошибка?

**Comment by KirilLoveVE** [comment]
Вышла новая версия 1.6.3.8 можете ее попробовать.
