### ISSUE TITLE
Авторизация без указания логина и пароля

### ISSUE THREAD

**Issue by zeyser** [KirilLoveVE/opencart2-exchange1c#12]
Сейчас каждый раз приходиться удалять exchange1c в полях Логин и Пароль Авторизации в случаях когда она тебе не нужна, а ты что-то зашел поправить в настройках. Мне кажется надо поменять  value на placeholder.

**Comment by KirilLoveVE** [comment]
Проблема есть, решу в ближайшее время, спасибо за найденную ошибку.
Как исправлю, обновлю модуль и отпишусь

**Comment by KirilLoveVE** [comment]
Проверьте последнюю версию модуля
