### ISSUE TITLE
Неправильно выгружаются торговые предложения

### ISSUE THREAD

**Issue by WouldYouKindly** [KirilLoveVE/opencart2-exchange1c#14]
Передаю в Opencart файлы [import.xml](https://drive.google.com/open?id=0B5_Q9ZdLAaZpUE8yTEw4a2xBcGs) и [offers.xml](https://drive.google.com/open?id=0B5_Q9ZdLAaZpS0k0ZnZNcHVTb1k). Там описан 1 товар с 4 предложенями, у каждого предложения по две характеристики.

В Opencart создаётся товар с тремя разновидностями. При этом на фронте магазина в селекте первой характеристики есть только одно из значений, а в селекте второй - одно значений второй, и одно значение первой характеристики (можно выбрать из 2 размера и зелёненького цвета). При это в списке характеристик у обеих правильные значения.

Версия Opencart: 2.0.3.1
Версия модуля: 1.6.1.13
Кроме модуля обмена ничего больше не стоит, чистая установка.

Почему такое может происходить?

**Comment by KirilLoveVE** [comment]
Только что загрузил Ваши файлы, посмотрите их работу на тестовом сервере
http://ocstore21021.ptr-print.ru/

**Comment by WouldYouKindly** [comment]
@KirilLoveVE со свойствами всё в порядке, но указана доступность - 3. А там 4 предложения, каждого по-одному.

А какая у вас там версия Opencart и плагина? На моём магазине, сколько бы я не удалял-загружал этот товар, предложения создаются неправильно.

**Comment by KirilLoveVE** [comment]
Возможно модификатор не установился правильно. Посмотрите нет ли ошибок типа NO FOUND! только там где модуль пытается внести изменения.

**Comment by WouldYouKindly** [comment]
Ошибок нет, есть только PHP Warning:  Invalid argument supplied for foreach() in .../admin/model/tool/exchange1c.php on line 321

Но это он на цены ругается. В остальном в логе чисто.

Я поставил свежий Опенкарт, накатил на него модуль - ситуация абсолютно аналогичная. Попробовал выгрузить другие товары (тоже с двумя свойствами) - ровно то же самое: остатки берутся из последнего предложения в файле, есть только 3 свойства из 4.

Если вдруг нужен, [вот лог](https://drive.google.com/open?id=0B5_Q9ZdLAaZpaFZ0bDJ1bnI3aDA)

Сегодня попробую ещё поставить Opencart 2.1.0.1 (он у вас тоже в списке поддерживаемых).

**Comment by KirilLoveVE** [comment]
В Вашем файле 2 товара в предложении, у первого Ид=jtOehEgCiaQLjW2hp94ec2 у него 3 характеристики, и последний с Ид=jtOehEgCiaQLjG4hp94ec2 с одной характеристикой, так как в импорте не прописан последний Ид, то модуль его не грузит и пишет в лог:
"Не найден товар по Ид jtOehEgCiaQLjG4hp94ec2"
для того чтобы товар отобразился в каталоге нужно прописать категории в них, а чтобы загрузились цены, нужно в классификаторе предложения указать используемые в товаре типы цен.

**Comment by WouldYouKindly** [comment]
Да, действительно, id неверные. Спасибо! К сожалению, причина проблемы не в этом.
Поднял Opencart 2.1.0.1. Версия модуля: 1.6.1.13. Выгрузил приложенные файлы (специально проверил - id у всех предложений совпадает; в логах тоже нет ошибок, все товары найдены). Ситуация такая же как и раньше: в товаре создались только три свойства. На фронте магазина в поле для одного свойства доступно для выбора значение другого.

![3](https://cloud.githubusercontent.com/assets/8452208/22469690/ec5c48a2-e7dd-11e6-9343-21e3261acb94.png)

[import.xml](https://drive.google.com/open?id=0B5_Q9ZdLAaZpQlhoUDRKdUlFNkk)
[offers.xml](https://drive.google.com/open?id=0B5_Q9ZdLAaZpUnJYSVFINGl1ZXM)

[log.txt](https://github.com/KirilLoveVE/opencart2-exchange1c/files/742317/log.txt)

**Comment by KirilLoveVE** [comment]
Модуль был переделан, новая версия 1.6.3 лучше работает с характеристиками
https://github.com/KirilLoveVE/opencart2-exchange1c/releases

**Comment by CrazyAdmin** [comment]
Здравствуйте. У меня почему то в опциях появляються 3 опции но не выгружаеться цена и количество.
Вы могли бы посмотреть в чем причина ? Версия модуля последняя. 
И да при скачивании модуля по этой ссылке - http://tesla-chita.ru/export/exchange1c.php?module=export там теряються некоторые файлы (В частности то что относиться к складам) Ни темплейта ни контроллера. И заметил что склады нельзя добавить. Нет формы. Или я не прав и в чемто ошибаюсь ?
Выгрузка: https://drive.google.com/open?id=1893xezRNJ4oWdbWyAUm1_Xw0WgLpUpYU
Там есть всего один товар с опциями - Тестовый товар 1

**Comment by KirilLoveVE** [comment]
> Здравствуйте. У меня почему то в опциях появляються 3 опции но не выгружаеться цена и количество.

Возможно проблема с модификаторами,

> И да при скачивании модуля по этой ссылке - http://tesla-chita.ru/export/exchange1c.php?module=export там теряються некоторые файлы (В частности то что относиться к складам) Ни темплейта ни контроллера. И заметил что склады нельзя добавить. Нет формы. Или я не прав и в чемто ошибаюсь ?

Склады нельзя добавить на сайте, они только из 1С управляются, на сайт они только добавляются, при изменении названия в 1С на сайте оно не изменится, я пока не уделял время складам.

Что касается ваших файлов я проверю позже, так как после множественных обновлений возможно не корректная загрузка этого формата XML

**Comment by KirilLoveVE** [comment]
Здравствуйте.
Сообщите мне 
1. конфигурацию 1С
2. версию сайта (opencart/ocstore)
3. версию модуля.
4. Включите в модуле обмена лог в режим "отладка + запросы"
5. Журнал ошибок веб-сервера если не включен, включите на хостинге
6. Сделайте обмен
7. Скиньте мне журнал ошибок opencart/ocstore
8. Если есть ошибки веб-сервера, то и журнал ошибок веб-сервера
После анализа я могу что-то посоветовать или сказать что еще где посмотреть. Склады только для вывода остатков, добавлять из 1С, пока еще проект со складами развивается.
В опциях есть ошибки, как раз по ним сейчас работаю.
Но Вы можете мне предоставить данные для анализа, анонимность информации гарантирую


>Среда, 18 апреля 2018, 22:46 +09:00 от Vladimir Nortsov <notifications@github.com>:
>
>Здравствуйте. У меня почему то в опциях появляються 3 опции но не выгружаеться цена и количество.
>Вы могли бы посмотреть в чем причина ? Версия модуля последняя.
>И да при скачивании модуля по этой ссылке -  http://tesla-chita.ru/export/exchange1c.php?module=export там теряються некоторые файлы (В частности то что относиться к складам) Ни темплейта ни контроллера. И заметил что склады нельзя добавить. Нет формы. Или я не прав и в чемто ошибаюсь ?
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С уважением, Виталий Е. Кириллов
email по личным вопросам 9145079035@mail.ru, mts4306000@gmail.com
Телефоны: +79145079035, +79144306000
