### ISSUE TITLE
Ошибки при обращении к /export/exchange1c.php

### ISSUE THREAD

**Issue by tolkodelo** [KirilLoveVE/opencart2-exchange1c#16]
код:
`require_once(DIR_SYSTEM . 'startup.php');
require_once(DIR_SYSTEM . 'library/currency.php');
require_once(DIR_SYSTEM . 'library/user.php');
require_once(DIR_SYSTEM . 'library/weight.php');
require_once(DIR_SYSTEM . 'library/length.php'); 
`
но у меня в папке нет таких файлов. Opencart 2.2.0.0

**Comment by tolkodelo** [comment]
закинул эти файлы в папку- сам импорт заработал, но товары в магазине не появляются

**Comment by tolkodelo** [comment]
Копаюсь в базе данных. Везде у товаров стоит Language_id = 0, меняю на 3 появляются в админке
в логе:
`2017-02-01 14:34:04 - 0475 | Получен language_id: 3`

**Comment by KirilLoveVE** [comment]
Этот модуль для opencart 2.1, для 2.2 не выпускался и будет сделан сразу для 2.3 и возможно он встанет как надо в 2.2, сейчас уже начата разработка для Opencart 2.3
Посмотреть можно тут http://opencart2302.ptr-print.ru/admin
логин/пароль: demo/demo

**Comment by tolkodelo** [comment]
После некоторого количества шаманства встал на 2.2 и работает )

**Comment by KirilLoveVE** [comment]
Вышел для 2.3
https://github.com/KirilLoveVE/opencart2-exchange1c/releases
