### ISSUE TITLE
Русский язык

### ISSUE THREAD

**Issue by tolkodelo** [KirilLoveVE/opencart2-exchange1c#19]
По умолчанию файл записался сюда:
/public_html/admin/language/russian/module
на странице модуля не показывался, я переместил сюда:
/public_html/admin/language/ru-ru/module
тогда заработал. Версия 1.6.2.b21
не первый раз с этим сталкиваюсь

**Comment by KirilLoveVE** [comment]
Это начиная с версии 2.2 пока под нее идет только разработка, поддержка начинается с версии 2.3

**Comment by tolkodelo** [comment]
Понятно.

Нам бы написать выгрузку фильтров, или копирование фильтров из характеристик, что-то через email не отвечаете. Можем это обсудить?

**Comment by KirilLoveVE** [comment]
Для версии 2.3 выпущен отдельный файл, версия такая же
https://github.com/KirilLoveVE/opencart2-exchange1c/releases
