### ISSUE TITLE
Примеры файлов участвующих в обмене

### ISSUE THREAD

**Issue by zeyser** [KirilLoveVE/opencart2-exchange1c#22]
Мне как воды не хватает примеров xml файлов. Я считаю должен быть пример с максимальным охватом всех возможностей и главное, который прошел тестирование и на 100% рабочий. Это хорошая отсылка в возможных спорах с 1С разработчиком.

**Comment by KirilLoveVE** [comment]
Вы можете прислать мне на почту свои файлы если они не проходят загрузку и я Вам скажу что с ними не так.
Есть несколько вариантов:
1. выгрузка из битрикс
2. выгрузка с характеристиками
3. порционная выгрузка
4. обмен заказами
Напишите мне на почту vitaly.kirillove@mail.ru я Вам вышлю примеры

**Comment by zeyser** [comment]
Да как-то неудобно дергать разработчика по таким мелочам... Я в целом в моей ситуации разобрался. Спасибо, что всегда готовы прийти на помощь!
