### ISSUE TITLE
Не создаётся таблица attribute_value

### ISSUE THREAD

**Issue by kolotalex** [KirilLoveVE/opencart2-exchange1c#25]
Добрый день после установки модуля в админке появилось сообщение 
 Таблица attribute_value в базе отсутствует!
 В вашем контроллере там где идёт создание таблиц в базе, нету 
чтото типа такого "CREATE TABLE `" . DB_PREFIX . "attribute_value` ( .....
в функции install  , или можно без неё обойтись , за какой функционал вообще она планировалась отвечать ?

**Comment by zeyser** [comment]
Я предполагаю это с атрибутами и связано. Если атрибуты не участвуют в обмене - то не критично.

**Comment by kolexndr** [comment]
Эта таблица создаётся в обновлении 1_6_2_b12.    Это обновление включено в актуальную версию модуля.  
Вы уверены, что используете последнюю версию модуля?

**Comment by KirilLoveVE** [comment]
Эта таблица используется при загрузке файлов XML 2.09 и выше выгруженные из 1С с модулем Битрикс, там файл с атрибутами выгружается отдельно, поэтому пришлось создать таблицу чтобы сохранить результаты до загрузки товаров. 
Вот страничка модуля на форуме: https://opencartforum.com/files/file/3123-modul-obmena-dlya-opencart-v2x-s-torgovoy-sistemoy-po-standartu-commerceml/

**Comment by KirilLoveVE** [comment]
Не прошли нужные обновления, 1.6.3 ставится как обновление только на 1.6.2.b28 или 1.6.2.b29
в других случаях надо вручную обновлять или переустанавливать модуль.

**Comment by kolotalex** [comment]
спасибо теперь понятно )
