### ISSUE TITLE
Create table SQL statement

### ISSUE THREAD

**Issue by valv-id** [KirilLoveVE/opencart2-exchange1c#4]
**MyISAM** Storage Engine Features: **Foreign key** support = **NO**
This ignored ??

\admin\model\tool\exchange1c.php, public function update162b4()
... 
**FOREIGN KEY** (`manufacturer_id`) REFERENCES `'. DB_PREFIX .'manufacturer`(`manufacturer_id`) ON DELETE CASCADE) ENGINE=**MyISAM**
...

\admin\controller\module\exchange1c.php, public function install() 
...
**FOREIGN KEY** (`product_id`) REFERENCES `'. DB_PREFIX .'product`(`product_id`) ON DELETE CASCADE) ENGINE=**MyISAM**
...
**FOREIGN KEY** (`category_id`) REFERENCES `'. DB_PREFIX .'category`(`category_id`) ON DELETE CASCADE) ENGINE=**MyISAM**
...
**FOREIGN KEY** (`attribute_id`) REFERENCES `'. DB_PREFIX .'attribute`(`attribute_id`) ON DELETE CASCADE) ENGINE=**MyISAM**
...
**FOREIGN KEY** (`option_id`) REFERENCES `'. DB_PREFIX .'option`(`option_id`) ON DELETE CASCADE) ENGINE=**MyISAM**
...
**FOREIGN KEY** (`manufacturer_id`) REFERENCES `'. DB_PREFIX .'manufacturer`(`manufacturer_id`) ON DELETE CASCADE) ENGINE=**MyISAM**
...
**FOREIGN KEY** (`store_id`) REFERENCES `'. DB_PREFIX .'store`(`store_id`) ON DELETE CASCADE) ENGINE=**MyISAM**
...

**Comment by valv-id** [comment]
Мне просто непонятно почему в opencart2 не перешли на таблицы InnoDB годы назад (за исключением таблицы oc_cart). Кроме поддержки транзакций, это дало бы и возможность использования FOREIGN KEY.

P.S. Если есть версия OpenCart 2.x, переписанная под использование InnoDB - упомяните ее хотя бы в комментариях)

**Comment by KirilLoveVE** [comment]
Вы правы, возможно из-за скорости работы? Может связи и нет уж важны, есть же события. Хотя при возникновении ошибок в скрипте, часть записей просто "подвисают" в базе.
