### ISSUE TITLE
Случайная и лишняя буква "m" в админке

### ISSUE THREAD

**Issue by vallhund** [KirilLoveVE/opencart2-exchange1c#5]
Видимо, что-то не полностью выделили при удалении, ну с кем не бывает?
![2016-07-24 23 42 11](https://cloud.githubusercontent.com/assets/1698538/17086467/6cb61830-51fb-11e6-816d-c33478f8a3f6.png)
![2016-07-24 23 59 31](https://cloud.githubusercontent.com/assets/1698538/17086468/6fd0a67a-51fb-11e6-9f4a-9bb3c2a88088.png)

Собственно, в opencart2-exchange1c/upload/admin/view/template/module/exchange1c.tpl
надо поправить строку 118 и все 

Пользуясь случаем, выражаю огромную благодарность за ваш модуль

**Comment by man5hatki** [comment]
Добрый день, а у Вас получилось его настроить ?

**Comment by vallhund** [comment]
**man5hatki**, в общем-то да

**Comment by KirilLoveVE** [comment]
Уже исправлена в следующих версиях
