### ISSUE TITLE
Не возможно копировать товар

### ISSUE THREAD

**Issue by yuriygr** [KirilLoveVE/opencart2-exchange1c#7]
После установки модификатора, который правит модель продукта, невозможно выполнить копирование продукта в списке товаров.

**Comment by KirilLoveVE** [comment]
В какой CMS Вы это делаете? В стандартной вроде нет такой функции.

**Comment by KirilLoveVE** [comment]
Проверил на ocstore 2.1.0.2.1 версия модуля 1.6.2.b24 все без проблем копируется

**Comment by KirilLoveVE** [comment]
Ошибка уже исправлена
https://github.com/KirilLoveVE/opencart2-exchange1c/releases
